import type { GetProductsResponseTypes } from '@pages/productList/types/api';

export const mockSearchData: GetProductsResponseTypes[] = [
  {
    productId: 1,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+1',
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    reviewCount: 100,
    categoryList: ['kitchen'],
    productTag: '인기',
  },
  {
    productId: 2,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+2',
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    reviewCount: 42,
    categoryList: ['kitchen'],
    productTag: '신상',
  },
  {
    productId: 3,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+3',
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    reviewCount: 87,
    categoryList: ['kitchen'],
    productTag: '할인',
  },
  {
    productId: 4,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
    categoryList: ['digital'],
    productTag: '인기',
  },
  {
    productId: 5,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
    categoryList: ['digital'],
    productTag: '신상',
  },
  {
    productId: 6,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+1',
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    reviewCount: 100,
    categoryList: ['kitchen'],
    productTag: '할인',
  },
  {
    productId: 7,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+2',
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    reviewCount: 42,
    categoryList: ['kitchen'],
    productTag: '인기',
  },
  {
    productId: 8,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+3',
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    reviewCount: 87,
    categoryList: ['kitchen'],
    productTag: '신상',
  },
  {
    productId: 9,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
    categoryList: ['digital'],
    productTag: '할인',
  },
  {
    productId: 10,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
    categoryList: ['digital'],
    productTag: '인기',
  },
  {
    productId: 11,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+1',
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    reviewCount: 100,
    categoryList: ['kitchen'],
    productTag: '신상',
  },
  {
    productId: 12,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+2',
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    reviewCount: 42,
    categoryList: ['kitchen'],
    productTag: '할인',
  },
  {
    productId: 13,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+3',
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    reviewCount: 87,
    categoryList: ['kitchen'],
    productTag: '인기',
  },
  {
    productId: 14,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
    categoryList: ['digital'],
    productTag: '신상',
  },
  {
    productId: 15,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
    categoryList: ['digital'],
    productTag: '할인',
  },
];
