import type { GetPromotionResponseTypes, GetProductsResponseTypes } from '@pages/home/types/api';
import { Category } from '@/pages/home/components/constant/categorys';

export const dummyCardsL: GetPromotionResponseTypes[] = [
  {
    productId: 1,
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+1',
  },
  {
    productId: 2,
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+2',
  },
  {
    productId: 3,
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+3',
  },
  {
    productId: 4,
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+4',
  },
  {
    productId: 5,
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+4',
  },
];

export const dummyCardsXL: GetProductsResponseTypes[] = [
  {
    productId: 1,
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+1',
    reviewCount: 100,
    productTag: '재구매 고객이 많은 스토어',
    categoryList: [Category.RECOMMEND],
  },
  {
    productId: 2,
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+2',
    reviewCount: 42,
    productTag: '한정 수량 특가',
    categoryList: [Category.KITCHEN],
  },
  {
    productId: 3,
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+3',
    reviewCount: 87,
    productTag: '디자인 인기 상품',
    categoryList: [Category.GOODS],
  },
  {
    productId: 4,
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+4',
    reviewCount: 130,
    productTag: '사무실 필수템',
    categoryList: [Category.DIGITAL],
  },
  {
    productId: 5,
    productName: '유아용 학습 장난감',
    discountRate: 12,
    discountPrice: 29000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+5',
    reviewCount: 67,
    productTag: '엄마들이 좋아하는',
    categoryList: [Category.BABY],
  },
  {
    productId: 6,
    productName: '헬스용 스마트워치',
    discountRate: 30,
    discountPrice: 72000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+6',
    reviewCount: 230,
    productTag: '헬창 필수 아이템',
    categoryList: [Category.SPORT],
  },
  {
    productId: 7,
    productName: '자동차 내부 클리너 세트',
    discountRate: 18,
    discountPrice: 19000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+7',
    reviewCount: 54,
    productTag: '운전자 인기템',
    categoryList: [Category.CAR],
  },
  {
    productId: 8,
    productName: '베스트셀러 자기계발서',
    discountRate: 8,
    discountPrice: 13500,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+8',
    reviewCount: 90,
    productTag: '2024 상반기 추천 도서',
    categoryList: [Category.BOOK],
  },
  {
    productId: 9,
    productName: '생필품 묶음 할인 세트',
    discountRate: 22,
    discountPrice: 23000,
    productImage: 'https://via.placeholder.com/350x150.png?text=Product+9',
    reviewCount: 76,
    productTag: '하루 특가 생필품',
    categoryList: [Category.NECESSITY],
  },
];
