import type { GetPromotionResponseTypes, GetProductsResponseTypes } from '@pages/home/types/api';
import { Category } from '@/pages/home/components/constant/categorys';

export const dummyCardsL: GetPromotionResponseTypes[] = [
  {
    size: 'l',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+1',
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    reviewCount: 100,
  },
  {
    size: 'l',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+2',
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    reviewCount: 42,
  },
  {
    size: 'l',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+3',
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    reviewCount: 87,
  },
  {
    size: 'l',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
  },
  {
    size: 'l',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
  },
];

export const dummyCardsXL: GetProductsResponseTypes[] = [
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+1',
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    reviewCount: 100,
    category: Category.RECOMMEND,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+2',
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    reviewCount: 42,
    category: Category.KITCHEN,
  },
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+3',
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    reviewCount: 87,
    category: Category.GOODS,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
    category: Category.DIGITAL,
  },
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+5',
    productName: '유아용 학습 장난감',
    discountRate: 12,
    discountPrice: 29000,
    reviewCount: 67,
    category: Category.BABY,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+6',
    productName: '헬스용 스마트워치',
    discountRate: 30,
    discountPrice: 72000,
    reviewCount: 230,
    category: Category.SPORT,
  },
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+7',
    productName: '자동차 내부 클리너 세트',
    discountRate: 18,
    discountPrice: 19000,
    reviewCount: 54,
    category: Category.CAR,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+8',
    productName: '베스트셀러 자기계발서',
    discountRate: 8,
    discountPrice: 13500,
    reviewCount: 90,
    category: Category.BOOK,
  },
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+9',
    productName: '생필품 묶음 할인 세트',
    discountRate: 22,
    discountPrice: 23000,
    reviewCount: 76,
    category: Category.NECESSITY,
  },
];
