import type { GetPromotionResponseTypes, GetProductsResponseTypes } from '@pages/home/types/api';

export const dummyCardsL: GetPromotionResponseTypes[] = [
  {
    size: 'l',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+1',
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    reviewCount: 100,
  },
  {
    size: 'l',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+2',
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    reviewCount: 42,
  },
  {
    size: 'l',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+3',
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    reviewCount: 87,
  },
  {
    size: 'l',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
  },
  {
    size: 'l',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
  },
] as const;
export const dummyCardsXL: GetProductsResponseTypes[] = [
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+1',
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    reviewCount: 100,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+2',
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    reviewCount: 42,
  },
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+3',
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    reviewCount: 87,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
  },
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+1',
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    reviewCount: 100,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+2',
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    reviewCount: 42,
  },
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+3',
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    reviewCount: 87,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
  },
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+1',
    productName: '모던 디자인 테이블 램프',
    discountRate: 20,
    discountPrice: 49000,
    reviewCount: 100,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+2',
    productName: '심플 미니멀 스탠드',
    discountRate: 15,
    discountPrice: 35000,
    reviewCount: 42,
  },
  {
    size: 'xl',
    repurchase: true,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+3',
    productName: '북유럽 스타일 조명',
    discountRate: 10,
    discountPrice: 59000,
    reviewCount: 87,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
  },
  {
    size: 'xl',
    repurchase: false,
    imageUrl: 'https://via.placeholder.com/350x150.png?text=Product+4',
    productName: 'LED 데스크 라이트',
    discountRate: 25,
    discountPrice: 41000,
    reviewCount: 130,
  },
] as const;
